// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzyfawsrdfthudmbuybj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6eWZhd3NyZGZ0aHVkbWJ1eWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjAzOTAsImV4cCI6MjA2NDYzNjM5MH0.IvGc21YjrXHNrr-6NBs_zByWP0PaxlKy9AdE6dofzmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);